name: Flutter Nightly Build
permissions:
  contents: write
on:
  schedule:
    # schedule build every night
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets:
      RENDEZVOUS_SERVER: ${{ secrets.RENDEZVOUS_SERVER }}
      RS_PUB_KEY: ${{ secrets.RS_PUB_KEY }}
    with:
      upload-artifact: true
      upload-tag: "nightly"
    permissions: 
      contents: write
